language: python

matrix:
  include:
    - python: 2.7

before_install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    bash miniconda.sh -b -p $HOME/miniconda;
    export PATH="$HOME/miniconda/bin:$PATH";
    hash -r;
    conda config --set always_yes yes --set changeps1 no;
    conda update -q conda;
    conda info -a;
    conda create -y -q -n freecad_cq3 -c cadquery -c conda-forge freecad=0.17 python=3.6 pyparsing conda mock coverage codecov;
    source ~/miniconda/bin/activate freecad_cq3;
  else
    sudo apt-get update -qq;
    sudo apt-get install -y freecad;
    pip install -r requirements-dev.txt;
    pip install travis-sphinx;
    pip install sphinx_rtd_theme;
    pip install readme_renderer;
  fi

install:
- python setup.py install;

script:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    python setup.py check -r -s;
  fi
- coverage run runtests.py
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    travis-sphinx build --nowarn --source=doc;
  fi

after_success:
- coverage xml
- codecov -X gcov --file coverage.xml

after_script:
- coveralls
- travis-sphinx deploy

branches:
  except:
  - pythonocc
  - 2_0_branch

deploy:
  provider: pypi
  user: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJGYzMzU2MGRkLTYxMzUtNDI3MS1iZmM5LTViODgzMmJmODFkNwACOXsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJjYWRxdWVyeSJdfSwgInZlcnNpb24iOiAxfQAABiAzceF5EivSLk4fAduzAOTGQMjxCVdwGy6sIZIu1U8uWw"
  on:
    branch: master
